apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy
data:
  proxy.conf: |
    server {
      stub_status on;
      listen 8042;
      listen 8088;
      listen 9864;
      listen 9870;
      server_tokens off;
      server_name _;
      client_max_body_size 0;
      chunked_transfer_encoding on;
      resolver 172.16.0.10;

      location / {
        proxy_pass http://$http_host;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_request_buffering off;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: true
      containers:
        - name: nginx
          image: nginx:1.23.0-alpine
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: config-volume
          configMap:
            name: proxy